export const programmingKeyWords = [
  // Programming Languages
  "JavaScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Go",
  "Rust",
  "TypeScript",
  "Perl",
  "R",
  "MATLAB",
  "Scala",
  "Objective-C",
  "Dart",
  "Haskell",
  "Lua",
  "Elixir",
  "Clojure",
  "F#",
  "Erlang",
  "VB.NET",
  "Groovy",
  "Shell",
  "HTML",
  "CSS",
  "SQL",
  "SAS",
  "Julia",
  "COBOL",
  "Fortran",
  "Ada",
  "Scheme",
  "Prolog",
  "Pascal",
  "Assembly",
  "Bash",
  "PowerShell",
  "Tcl",
  "VHDL",
  "Verilog",
  "Racket",
  "OCaml",
  "Smalltalk",
  "Crystal",
  "Nim",
  "Solidity",
  "Apex",
  "Awk",
  "D",
  "ActionScript",
  "Forth",
  "Io",
  "Logo",
  "ML",
  "Pike",
  "PostScript",
  "REXX",
  "RPG",
  "Simula",

  // Programming Terminologies
  "Algorithm",
  "Array",
  "Function",
  "Variable",
  "Object",
  "Class",
  "Inheritance",
  "Encapsulation",
  "Polymorphism",
  "Abstraction",
  "Interface",
  "Method",
  "Loop",
  "Conditional",
  "Recursion",
  "Compilation",
  "Interpreter",
  "IDE",
  "Framework",
  "Library",
  "SDK",
  "API",
  "Version Control",
  "Repository",
  "Branch",
  "Merge",
  "Commit",
  "Pull Request",
  "Data Structure",
  "Stack",
  "Queue",
  "Linked List",
  "Tree",
  "Graph",
  "Hash Table",
  "Database",
  "Normalization",
  "Transaction",
  "Concurrency",
  "Parallelism",
  "Big O Notation",
  "Syntax",
  "Semantics",
  "Exception",
  "Error Handling",
  "Debugging",
  "Testing",
  "Unit Test",
  "Integration Test",
  "Deployment",
  "Continuous Integration",
  "Continuous Deployment",
  "Agile",
  "Scrum",
  "Kanban",
  "DevOps",
  "Microservices",
  "Monolith",
  "Cloud Computing",
  "Serverless",
  "Containerization",
  "Virtualization",
  "HTTP",
  "REST",
  "SOAP",
  "GraphQL",
  "WebSocket",
  "OAuth",
  "JWT",
  "SSL/TLS",
  "Encryption",
  "Authentication",
  "Authorization",
  "Frontend",
  "Backend",
  "Full Stack",
  "Responsive Design",
  "Progressive Web App",
  "Single Page Application",
  "MVC",
  "MVVM",
  "State Management",
  "Redux",
  "Context API",
  "Hook",
  "Component",
  "Directive",
  "Service",
  "Dependency Injection",
  "Event Loop",
  "Callback",
  "Promise",
  "Async/Await",
  "Thread",
  "Process",
  "Garbage Collection",
  "Memory Management",
  "Pointer",
  "Reference",
  "Immutable",
  "Mutable",
  "Prototype",
  "Closure",
  "Higher-order Function",
  "Currying",
  "Partial Application",
  "Side Effect",
  "Pure Function",
  "Functional Programming",
  "Object-Oriented Programming",
  "Procedural Programming",
  "Declarative Programming",
  "Imperative Programming",
  "Middleware",
  "ORM (Object-Relational Mapping)",
  "NoSQL",
  "ACID",
  "BASE",
  "CAP Theorem",
  "Load Balancing",
  "Caching",
  "Reverse Proxy",
  "API Gateway",
  "Rate Limiting",
  "Circuit Breaker",
  "Service Discovery",
  "Event-Driven Architecture",
  "CQRS (Command Query Responsibility Segregation)",
  "Domain-Driven Design",
  "Event Sourcing",
  "Distributed Systems",
  "MapReduce",
  "Data Warehouse",
  "Data Lake",
  "ETL (Extract, Transform, Load)",
  "Data Pipeline",
  "Business Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Neural Network",
  "Natural Language Processing",
  "Computer Vision",
  "Reinforcement Learning",
  "Supervised Learning",
  "Unsupervised Learning",
  "Feature Engineering",
  "Model Training",
  "Hyperparameter Tuning",
  "Cross-Validation",
  "Gradient Descent",
  "Backpropagation",
  "Overfitting",
  "Underfitting",
  "Regularization",
  "Clustering",
  "Classification",
  "Regression",
  "Recommendation System",
  "Time Series Analysis",
  "Big Data",
  "Hadoop",
  "Spark",
  "Kafka",
  "Flink",
  "Storm",
  "Data Mining",
  "Web Scraping",
  "Blockchain",
  "Smart Contract",
  "Cryptocurrency",
  "Distributed Ledger",
  "Peer-to-Peer Network",
  "Consensus Algorithm",
  "Proof of Work",
  "Proof of Stake",
  "Hash Function",
  "Digital Signature",
  "Cryptographic Key",
  "Public Key Infrastructure",
  "Zero-Knowledge Proof",
  "Homomorphic Encryption",
  "Quantum Computing",
  "Qubit",
  "Quantum Entanglement",
  "Quantum Supremacy",
  "Quantum Algorithm",
  "Shor's Algorithm",
  "Grover's Algorithm",
  "Quantum Cryptography",
  "IoT (Internet of Things)",
  "Edge Computing",
  "Fog Computing",
  "Sensor Network",
  "Wearable Technology",
  "Smart Home",
  "Connected Car",
  "Industrial IoT",
  "Digital Twin",
  "Augmented Reality",
  "Virtual Reality",
  "Mixed Reality",
  "3D Rendering",
  "Game Development",
  "Game Engine",
  "Shader",
  "Physics Engine",
  "Artificial Intelligence",
  "NPC (Non-Player Character)",
  "Procedural Generation",
  "Asset Pipeline",
  "DevTools",
  "Compiler",
  "Interpreter",
  "JIT (Just-In-Time Compilation)",
  "Build System",
  "Package Manager",
  "Containerization",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Chef",
  "Puppet",
  "Infrastructure as Code",
  "Monitoring",
  "Logging",
  "Alerting",
  "Tracing",
  "Telemetry",
  "Analytics",
  "Business Metrics",
  "User Metrics",
  "Conversion Funnel",
  "A/B Testing",
  "Multivariate Testing",
  "Feature Flag",
  "Canary Release",
  "Blue-Green Deployment",
  "Infrastructure Monitoring",
  "Application Performance Monitoring",
  "Security",
  "Penetration Testing",
  "Vulnerability Assessment",
  "Threat Modeling",
  "Incident Response",
  "Forensics",
  "Compliance",
  "GDPR",
  "HIPAA",
  "SOC 2",
  "ISO 27001",
  "Security Operations Center",
  "Identity and Access Management",
  "Single Sign-On",
  "Multi-Factor Authentication",
  "Role-Based Access Control",
  "Principle of Least Privilege",
  "Secure Coding",
  "Static Analysis",
  "Dynamic Analysis",
  "Security Testing",
  "Exploit",
  "Malware",
  "Phishing",
  "Ransomware",
  "Denial of Service",
  "Man-in-the-Middle",
  "SQL Injection",
  "Cross-Site Scripting",
  "Cross-Site Request Forgery",
  "Buffer Overflow",
  "Zero-Day Vulnerability",
  "Patch Management",
  "Threat Intelligence",
  "Bug Bounty",
  "Secure Development Lifecycle",
  "Application Security",
  "Network Security",
  "Endpoint Security",
  "Cloud Security",
  "DevSecOps",
  "Security Information and Event Management",
  "Vulnerability Management",
  "Incident Management",
  "Risk Management",
  "Business Continuity",
  "Disaster Recovery",
  "Data Backup",
  "Data Recovery",
  "Encryption",
  "Decryption",
  "Digital Certificate",
  "Public Key",
  "Private Key",
  "Certificate Authority",
  "Key Management",
  "Tokenization",
  "Data Masking",
  "Privacy",
  "Anonymization",
  "Pseudonymization",
  "Differential Privacy",
  "Homomorphic Encryption",
  "Federated Learning",
  "Data Governance",
  "Data Lineage",
  "Data Stewardship",
  "Data Quality",
  "Master Data Management",
  "Data Integration",
  "Data Migration",
  "Data Lake",
  "Data Warehouse",
  "Data Mart",
  "Data Fabric",
  "Data Mesh",
  "Metadata Management",
  "Data Catalog",
  "Data Dictionary",
  "Data Pipeline",
  "ETL",
  "ELT",
  "Data Modeling",
  "Data Architecture",
  "Data Strategy",
  "Data Analytics",
  "Descriptive Analytics",
  "Diagnostic Analytics",
  "Predictive Analytics",
  "Prescriptive Analytics",
  "Data Visualization",
  "Dashboard",
  "Report",
  "Business Intelligence",
  "Data Science",
  "Machine Learning",
  "Deep Learning",
  "Artificial Intelligence",
  "Natural Language Processing",
  "Computer Vision",
  "Reinforcement Learning",
  "Supervised Learning",
  "Unsupervised Learning",
  "Feature Engineering",
  "Model Training",
  "Hyperparameter Tuning",
  "Cross-Validation",
  "Gradient Descent",
  "Backpropagation",
  "Overfitting",
  "Underfitting",
  "Regularization",
  "Clustering",
  "Classification",
  "Regression",
  "Recommendation System",
  "Time Series Analysis",
  "Big Data",
  "Hadoop",
  "Spark",
  "Kafka",
  "Flink",
  "Storm",
  "Data Mining",
  "Web Scraping",
  "Blockchain",
  "Smart Contract",
  "Cryptocurrency",
  "Distributed Ledger",
  "Peer-to-Peer Network",
  "Consensus Algorithm",
  "Proof of Work",
  "Proof of Stake",
  "Hash Function",
  "Digital Signature",
  "Cryptographic Key",
  "Public Key Infrastructure",
  "Zero-Knowledge Proof",
  "Homomorphic Encryption",
  "Quantum Computing",
  "Qubit",
  "Quantum Entanglement",
  "Quantum Supremacy",
  "Quantum Algorithm",
  "Shor's Algorithm",
  "Grover's Algorithm",
  "Quantum Cryptography",
  "IoT",
  "Edge Computing",
  "Fog Computing",
  "Sensor Network",
  "Wearable Technology",
  "Smart Home",
  "Connected Car",
  "Industrial IoT",
  "Digital Twin",
  "Augmented Reality",
  "Virtual Reality",
  "Mixed Reality",
  "3D Rendering",
  "Game Development",
  "Game Engine",
  "Shader",
  "Physics Engine",
  "Artificial Intelligence",
  "NPC",
  "Procedural Generation",
  "Asset Pipeline",
  "DevTools",
  "Compiler",
  "Interpreter",
  "JIT",
  "Build System",
  "Package Manager",
  "Containerization",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Chef",
  "Puppet",
  "Infrastructure as Code",
  "Monitoring",
  "Logging",
  "Alerting",
  "Tracing",
  "Telemetry",
  "Analytics",
  "Business Metrics",
  "User Metrics",
  "Conversion Funnel",
  "A/B Testing",
  "Multivariate Testing",
  "Feature Flag",
  "Canary Release",
  "Blue-Green Deployment",
  "Infrastructure Monitoring",
  "Application Performance Monitoring",
  "Security",
  "Penetration Testing",
  "Vulnerability Assessment",
  "Threat Modeling",
  "Incident Response",
  "Forensics",
  "Compliance",
  "GDPR",
  "HIPAA",
  "SOC 2",
  "ISO 27001",
  "Security Operations Center",
  "Identity and Access Management",
  "Single Sign-On",
  "Multi-Factor Authentication",
  "Role-Based Access Control",
  "Principle of Least Privilege",
  "Secure Coding",
  "Static Analysis",
  "Dynamic Analysis",
  "Security Testing",
  "Exploit",
  "Malware",
  "Phishing",
  "Ransomware",
  "Denial of Service",
  "Man-in-the-Middle",
  "SQL Injection",
  "Cross-Site Scripting",
  "Cross-Site Request Forgery",
  "Buffer Overflow",
  "Zero-Day Vulnerability",
  "Patch Management",
  "Threat Intelligence",
  "Bug Bounty",
  "Secure Development Lifecycle",
  "Application Security",
  "Network Security",
  "Endpoint Security",
  "Cloud Security",
  "DevSecOps",
  "Security Information and Event Management",
  "Vulnerability Management",
  "Incident Management",
  "Risk Management",
  "Business Continuity",
  "Disaster Recovery",
  "Data Backup",
  "Data Recovery",
  "HTTP",
  "API",
];
